version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    entrypoint:  dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    restart: always
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on: 
      - db   

  db:
    image: mysql:8.3.0
    command: --default-authentication-plugin=caching_sha2_password   
    restart: always
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password  

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"

volumes:
  mysql-data: